setup:
  addons:
    - plan: heroku-postgresql
      as: DATABASE
    - plan: heroku-redis
      as: QUEUE
    - plan: heroku-scheduler
      as: SCHEDULER
build:
  languages:
    - ruby
  config:
    RACK_ENV: production
    AUTH_SERVICE: static
    PORT: 5000
release:
  command:
    - bin/migrate
run:
  web: bundle exec rackup -p $PORT
  workers: bundle exec sidekiq -C ./config/sidekiq.yml -r ./config/sidekiq.rb
