
---
replicated_api_version: "1.0.0"
name: "EBICS::Box"
version: "0.0.83"
release_notes: ""
components:
- name: Postgresql
  containers:
  - source: public
    image_name: "postgres"
    version: 9.6.1-alpine
    publish_events:
    - name: Container Postgres started
      trigger: container-start
      data: ""
      subscriptions:
      - component: BOX
        container: ebicsbox
        action: start
    env_vars:
    - name: POSTGRES_PASSWORD
      static_val: "mysecretpassword"
    - name: POSTGRES_USER
      static_val: "ebicsbox"
    ports:
    - private_port: "5432"
      public_port: "5432"
      port_type: tcp
      interface: docker0
      when: ""
    volumes:
    - host_path: /data-postgresql
      container_path: /var/lib/postgresql/data
- name: Redis
  containers:
  - source: public
    image_name: redis
    version: latest
    publish_events:
    - name: Container Redis started
      trigger: container-start
      data: ""
    ports:
    - private_port: "6379"
      public_port: "6379"
      port_type: tcp
      interface: docker0
      when: ""
- name: BOX
  containers:
  - source: replicated
    image_name: ebicsbox
    version: 0.7.2
    config_files: []
    customer_files: []
    env_vars:
    - name: USERNAME
      static_val: "{{repl ConfigOption \"username\" }}"
    - name: PASSWORD
      static_val: "{{repl ConfigOption \"password\" }}"
    - name: DATABASE_URL
      static_val: "postgresql://{{repl InterfaceAddress \"docker0\" }}/ebicsbox?user=ebicsbox&password=mysecretpassword"
    - name: EBICS_CLIENT
      static_val: "Epics::Client"
    - name: PORT
      static_val: "5000"
    - name: RACK_ENV
      static_val: "production"
    - name: VIRTUAL_HOST
      static_val: "{{repl ConfigOption \"virtual_host\" }}"
    - name: ALLOW_REGISTRATIONS
      static_val: "enabled"
    - name: APP_URL
      static_val: "{{repl ConfigOption \"app_url\" }}"
    ports:
    - private_port: "5000"
      public_port: "5000"
      port_type: tcp
      when: ""
    support_files: []
- name: nginx
  containers:
  - source: public
    image_name: jwilder/nginx-proxy
    version: latest
    volumes:
    - host_path: "{{repl ConfigOption \"certs_path\" }}"
      container_path: /etc/nginx/certs
    - host_path: /var/run/docker.sock
      container_path: /tmp/docker.sock
    ports:
    - private_port: "80"
      public_port: "80"
      port_type: tcp
      when: ""
    - private_port: "443"
      public_port: "443"
      port_type: tcp
      when: ""
backup:
  enabled: false
  init: []
  run: []
cmds: []
config:
- name: authentication
  title: Authentication
  description: These are the Basic Auth credentials used by your EBCIS::Box
  items:
  - name: username
    title: Username
    type: text
    recommended: true
  - name: password
    title: Password
    type: password
    recommended: true
- name: key_passphrase
  title: Passphrase
  description: To protect your EBCIS keys
  items:
  - name: passphrase
    title: Passphrase
    type: password
    required: true
- name: nginx
  title: Nginx Settings
  description: Define some important things!
  items:
  - name: certs_path
    title: Certificate Path
    type: text
    required: true
  - name: virtual_host
    title: Virtual host for ebicsbox
    type: text
    required: true
  - name: app_url
    title: App URL for documentation
    type: text
    required: true
