apiVersion: v1alpha
kind: Notification
metadata:
  name: notify-ebicsbox
spec:
  rules:
    - name: "Pipeline failed 🔥"
      filter:
        projects:
          - ebicsbox
        results:
          - failed
      notify:
        slack:
          endpoint: https://hooks.slack.com/services/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
          channels:
            - "#ebicsbox"
    - name: "build docker:latest 🐳📦✨"
      filter:
        projects:
          - ebicsbox
        pipelines:
          - docker-latest.yml
        results:
          - passed
      notify:
        slack:
          endpoint: https://hooks.slack.com/services/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
          channels:
            - "#ebicsbox"
    - name: "build docker:tag 🐳📦🔐"
      filter:
        projects:
          - ebicsbox
        pipelines:
          - docker-tag.yml
        results:
          - passed
      notify:
        slack:
          endpoint: https://hooks.slack.com/services/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
          channels:
            - "#ebicsbox"
